######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 19:59:30 2008
######################################################################
ICON = resources/H_icon.icns

TEMPLATE = app
TARGET = 
DEPENDPATH += .

INCLUDEPATH += /opt/local/include

SOURCES += main.cpp \
    MainWindow.cpp

HEADERS += \
    MainWindow.h

RESOURCES += \
    resources.qrc

